name: push-check

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare env file
        run: cd app && make prepare-env

      - name: Run tests
        run: make docker-tests

      - name: Build docker image
        run: make docker-build

      - name: Docker login
        run: docker login --username=${{ secrets.DOCKER_ID }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: make docker-push

